Repair Chinese name folder or file cannot be copied
fangfufu/httpdirfs pull request #70
Opened 2021-07-27 13:59 UTC by MecryWork

When mounting an HTTP file server in deepin, the Chinese name folder cannot be correctly recognized and is processed as a file

2021-07-27 14:00 UTC, MecryWork commented
![截图_选择区域_20210727215833](https://user-images.githubusercontent.com/59426901/127167282-15e08494-db98-49f0-9ee3-78f59348a993.png)

2021-07-27 17:43 UTC, fangfufu commented
Could you squash your 5 commits into 1, please?

2021-07-27 17:50 UTC, fangfufu commented on src/link.c
> +            if(linkname[strnlen(linkname, MAX_FILENAME_LEN) - 1] == '/') {
We don't need this, because it checks for ``'/'`` later down the code.

2021-07-27 17:50 UTC, fangfufu commented on src/link.c
>      if (!isalnum(linkname[0])) {
Maybe replace this with a better function?

2021-07-27 17:52 UTC, fangfufu requested changes
Is there a theoretical basis of why ``"%E"`` all lead to Chinese characters?

2021-07-28 01:26 UTC, MecryWork commented
Because if it is a Chinese file or folder, the beginning is `%E`, and `/` is to distinguish between Chinese files and medium files

2021-07-28 01:26 UTC, MecryWork commented
![image](https://user-images.githubusercontent.com/59426901/127248868-b6eff09c-06ed-4ffd-9ee1-1610416c49ae.png)

2021-07-28 01:28 UTC, MecryWork commented
Chinese open files and text are not recognized

2021-07-28 02:22 UTC, MecryWork commented
Chinese name file and text are not recognized

2021-07-28 02:23 UTC, MecryWork commented
Files or folders beginning with Chinese names are not recognized

2021-07-28 18:08 UTC, fangfufu commented
I am not going to merge your patch as it is. 

The check for ``'/'`` is performed at https://github.com/fangfufu/httpdirfs/blob/master/src/link.c#L123. I don't see the reason why you want to add an additional check.

I can see that a lot of Chinese characters start with ``%E``, but I don't understand why that is the case.

2021-07-29 01:13 UTC, MecryWork commented
> When mounting an HTTP file server in deepin, the Chinese name folder cannot be correctly recognized and is processed as a file

2021-07-29 01:13 UTC, closed without merging

2021-08-04 23:35 UTC, fangfufu commented
Hi, this is fixed in 861481e6e1ab372370e724b61864c07d35d98632